### ISSUE TITLE
Mirror template workload to a number of collections

### ISSUE THREAD

**Issue by alex-thc** [schambon/SimRunner#20]
Right now there's a 1:1 relationship between a template and a workload. Would love to have the ability to instantiate the template multiple times as different collections and mirror the associated workload to these collections.

E.g. for a template "person":
{
      "name": "person",
      "database": "simrunner",
      "collection": "people"
}, 

I want to set a parameter "instances: 500", and have the workloads associated with the template be mirrored across collections "people_1"..."people_500"

**Comment by schambon** [comment]
Hey @alex-thc,

Can you check out this branch: https://github.com/schambon/SimRunner/tree/20-template-instances

If that works for you, I’ll merge to master.
