### ISSUE TITLE
Support for time-series loading patterns

### ISSUE THREAD

**Issue by jbrannst** [schambon/SimRunner#22]
I'm trying to get sumrunner to insert time series data in batches of 16 in a way that preserves a continuous series of records for a device. I'd like 11,000 series to start at timeX and increment time by 15 minutes until time is X+3 years (but that's not a hard deadline per se) and insert such records in batches of 16.

I can fairly easily set up 11k devices loading batches of 16 records each 1 minute incremental offset but that's a global counter so to get the right number of records the timestamp will extend far into the future and definitely not honor basic assumptions about a time series..

**Comment by schambon** [comment]
Hi, please take a look at this branch: https://github.com/schambon/SimRunner/tree/timeseries#timeseries
It doesn't do everything yet (no batch writes to start with) but I'd welcome your opinion.

**Comment by schambon** [comment]
Closing this as initial support for timeseries has been merged.
